# Generated by Django 4.1.3 on 2025-08-18 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_ovos', models.CharField(choices=[('CODORNAS', 'Codornas (17 dias)'), ('GALINHAS', 'Galinhas (21 dias)'), ('PERSONALIZADO', 'Personalizado')], max_length=20)),
                ('dias_personalizados', models.PositiveIntegerField(blank=True, help_text='Se vazio, usa padrão do tipo de ovos', null=True)),
                ('inicio_incubacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-inicio_incubacao'],
            },
        ),
    ]
