# Generated by Django 4.2.7 on 2025-08-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='tipo_ovos',
            field=models.CharField(choices=[('CODORNA', 'Codorna (17 dias)'), ('GALINHA', 'Galinha (21 dias)'), ('GALINHA DA ANGOLA', 'Galinhas da Angola(26 a 28 dias)'), ('PERU', 'Perú (28 dias)'), ('PERSONALIZADO', 'Personalizado')], max_length=20),
        ),
    ]
