# Generated by Django 5.2.5 on 2025-09-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('FREE', 'Free'), ('PAGO', 'Pago')], default='FREE', help_text='Tipo de usuário: Free (1 lote) ou Pago (ilimitado)', max_length=10),
        ),
    ]
